import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = process.cwd();
const MEDIA_FILE = join(ROOT, 'src', 'data', 'enrichedMedia.ts');
const OUTPUT_FILE = join(ROOT, 'supabase', 'seed_media.sql');

function readMedia() {
  const source = readFileSync(MEDIA_FILE, 'utf8').replace(/^\uFEFF/, '');
  const match = source.match(/export const enrichedMedia: MediaItem\[] = ([\s\S]*);\s*$/);
  if (!match) throw new Error('Cannot parse enrichedMedia.ts');
  return JSON.parse(match[1]);
}

function sql(value) {
  if (value === undefined || value === null || value === '') return 'null';
  if (typeof value === 'number') return Number.isFinite(value) ? String(value) : 'null';
  if (typeof value === 'boolean') return value ? 'true' : 'false';
  return `'${String(value).replaceAll("'", "''")}'`;
}

function sqlText(value) {
  return `'${String(value || '').replaceAll("'", "''")}'`;
}

function textArray(values = []) {
  if (!values.length) return 'array[]::text[]';
  return `array[${values.map(sql).join(', ')}]::text[]`;
}

const rows = readMedia();
const statements = rows.map((item) => `(
  ${sqlText(item.id)},
  ${sqlText(item.titleRu)},
  ${sql(item.titleOriginal)},
  ${sqlText(item.type)},
  ${sql(item.year)},
  ${sqlText(item.posterUrl)},
  ${sql(item.backdropUrl)},
  ${sqlText(item.description)},
  ${textArray(item.genres)},
  ${textArray(item.countries)},
  ${sql(item.tmdbId)},
  ${sql(item.kinopoiskId)},
  ${sql(item.imdbId)},
  ${sql(item.kinopoiskRating)},
  ${sql(item.imdbRating)},
  ${sql(item.myRating)},
  ${sql(item.myReview)},
  ${sql(item.watchedAt)},
  ${sql(item.addedAt)},
  ${sql(Boolean(item.isFavorite))},
  ${sql(Boolean(item.isTop))},
  ${sql(item.topRank)},
  ${sql(Boolean(item.rewatch))}
)`).join(',\n');

const output = `-- Generated by scripts/exportSupabaseSeed.mjs
-- Run supabase/schema.sql first.

insert into media_items (
  id,
  title_ru,
  title_original,
  type,
  year,
  poster_url,
  backdrop_url,
  description,
  genres,
  countries,
  tmdb_id,
  kinopoisk_id,
  imdb_id,
  kinopoisk_rating,
  imdb_rating,
  my_rating,
  my_review,
  watched_at,
  added_at,
  is_favorite,
  is_top,
  top_rank,
  rewatch
)
values
${statements}
on conflict (id) do update set
  title_ru = excluded.title_ru,
  title_original = excluded.title_original,
  type = excluded.type,
  year = excluded.year,
  poster_url = excluded.poster_url,
  backdrop_url = excluded.backdrop_url,
  description = excluded.description,
  genres = excluded.genres,
  countries = excluded.countries,
  tmdb_id = excluded.tmdb_id,
  kinopoisk_id = excluded.kinopoisk_id,
  imdb_id = excluded.imdb_id,
  kinopoisk_rating = excluded.kinopoisk_rating,
  imdb_rating = excluded.imdb_rating,
  my_rating = excluded.my_rating,
  my_review = excluded.my_review,
  watched_at = excluded.watched_at,
  added_at = excluded.added_at,
  is_favorite = excluded.is_favorite,
  is_top = excluded.is_top,
  top_rank = excluded.top_rank,
  rewatch = excluded.rewatch,
  updated_at = now();
`;

mkdirSync(join(ROOT, 'supabase'), { recursive: true });
writeFileSync(OUTPUT_FILE, output, 'utf8');
console.log(`Wrote ${rows.length} media rows to ${OUTPUT_FILE}`);
